---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm
spec:
  deployStrategy:
    deploy: true
  nodes: # This will be NodeSection instead of NodeSpec
    env:
      - name: ANSIBLE_FORCE_COLOR
        value: "True"
      - name: ANSIBLE_ENABLE_TASK_DEBUGGER
        value: "True"
      - name: ANSIBLE_VERBOSITY
        value: "2"
    # Defining pre-provisioned servers that don't require provisioning
    edpm-compute-0:
      ansibleHost: 172.20.12.67
      ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
      ansibleUser: root
      # Ansible variables here override ansibleVars defined at the top level.
      # This allows for node specific overrides.
      ansibleVars: |
        ctlplane_ip: 172.20.12.67
        internal_api_ip: 172.17.0.101
        storage_ip: 172.18.0.101
        tenant_ip: 172.10.0.101
        external_ip: 172.20.12.76
        fqdn_internal_api: edpm-compute-1.example.com
        ansible_ssh_transfer_method: scp
    edpm-compute-1:
      hostName: edpm-compute-1
      preProvisioned: true
      # If we need to provision nodes, we can do so via the baremetalSetTemplate
      baremetalSetTemplate:
        deploymentSSHSecret: dataplane-ansible-ssh-private-key-secret
        bmhLabelSelector:
          app: openstack
        ctlplaneInterface: enp1s0
        dnsSearchDomains:
          - osptest.openstack.org
        managementNetwork: CtlPlane
      networks:
       - name: CtlPlane
         subnetName: subnet1
         defaultroute: true
       - name: InternalApi
         subnetName: subnet1
       - name: Storage
         subnetName: subnet1
       - name: Tenant
         subnetName: subnet1
  ansibleUser: cloud-admin
  ansiblePort: 22
  # If no node specific ansibleVars are provided, we will default to the values
  # provided here.
  ansibleVars: |
      service_net_map:
        nova_api_network: internal_api
        nova_libvirt_network: internal_api
      edpm_chrony_ntp_servers:
        - 0.pool.ntp.org
        - 1.pool.ntp.org
      # edpm_network_config
      # Default nic config template for a EDPM compute node
      # These vars are edpm_network_config role vars
      edpm_network_config_template: templates/single_nic_vlans/single_nic_vlans.j2
      edpm_network_config_hide_sensitive_logs: false
      # These vars are for the network config templates themselves and are
      # considered EDPM network defaults.
      neutron_physical_bridge_name: br-ex
      neutron_public_interface_name: eth0
      role_networks:
      - InternalApi
      - Storage
      - Tenant
      networks_lower:
        External: external
        InternalApi: internal_api
        Storage: storage
        Tenant: tenant
