apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: openstackdataplaneservice-sample
spec:
  label: your-label-here
  playbook: playbook-to-execute
  ansibleAnyErrorsFatal: true
  ansibleMaxFailPercentage: 10
