apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNode
metadata:
  name: openstackdataplanenode-sample
spec:
  role: openstackdataplanerole-sample
  hostName: openstackdataplanenode-sample.localdomain
  ansibleHost: 192.168.122.18
  node:
    networks:
      - network: ctlplane
        fixedIP: 192.168.122.18
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    networkConfig:
      template: |
          ---
          {% set control_virtual_ip = net_vip_map.ctlplane %}
          {% set public_virtual_ip = vip_port_map.external.ip_address %}
          {% if ':' in control_virtual_ip %}
          {%   set control_virtual_cidr = 128 %}
          {% else %}
          {%   set control_virtual_cidr = 32 %}
          {%   endif %}
          {% if ':' in public_virtual_ip %}
          {%   set public_virtual_cidr = 128 %}
          {% else %}
          {%   set public_virtual_cidr = 32 %}
          {%   endif %}
          network_config:
          - type: ovs_bridge
            name: br-ctlplane
            use_dhcp: false
            mtu: {{ ctlplane_mtu }}
            ovs_extra:
            - br-set-external-id br-ctlplane bridge-id br-ctlplane
            addresses:
            - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_subnet_cidr }}
            - ip_netmask: {{ control_virtual_ip}}/{{ control_virtual_cidr }}
            - ip_netmask: {{ public_virtual_ip}}/{{ public_virtual_cidr }}
            routes: {{ ctlplane_host_routes }}
            dns_servers: {{ ctlplane_dns_nameservers }}
            domain: {{ dns_search_domains }}
            members:
              - type: interface
                name: {{ neutron_public_interface_name }}
                primary: true
                mtu: {{ ctlplane_mtu }}
