apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm
spec:
  services:
    - download-cache
    - bootstrap
    - configure-network
    - validate-network
    - frr
    - install-os
    - configure-os
    - run-os
    - install-certs
    - ovn
    - neutron-metadata
    - ovn-bgp-agent
    - libvirt
    - nova
    - telemetry
  preProvisioned: true
  nodes:
      edpm-compute-0:
        hostName: edpm-compute-0
        ansible:
          ansibleHost: 192.168.122.100
  networkAttachments:
    - ctlplane
  nodeTemplate:
    networks:
      - name: CtlPlane
        subnetName: subnet1
        defaultRoute: true
      - name: InternalApi
        subnetName: subnet1
      - name: Storage
        subnetName: subnet1
      - name: Tenant
        subnetName: subnet1
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    ansible:
      ansibleVars:
         # edpm_network_config
         # Default nic config template for a EDPM compute node
         # These vars are edpm_network_config role vars
         edpm_network_config_hide_sensitive_logs: false
         edpm_network_config_template: |
              ---
              {% set mtu_list = [ctlplane_mtu] %}
              {% for network in role_networks %}
              {{ mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) }}
              {%- endfor %}
              {% set min_viable_mtu = mtu_list | max %}
              network_config:
              - type: interface
                name: nic1
                mtu: {{ ctlplane_mtu }}
                dns_servers: {{ ctlplane_dns_nameservers }}
                domain: {{ dns_search_domains }}
                use_dhcp: false
                addresses:
                - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}
              {% for network in role_networks %}
              {% if lookup('vars', networks_lower[network] ~ '_vlan_id', default='') %}
              - type: vlan
                device: nic1
                mtu: {{ lookup('vars', networks_lower[network] ~ '_mtu') }}
                vlan_id: {{ lookup('vars', networks_lower[network] ~ '_vlan_id') }}
                addresses:
                - ip_netmask:
                    {{ lookup('vars', networks_lower[network] ~ '_ip') }}/{{ lookup('vars', networks_lower[network] ~ '_cidr') }}
                routes: {{ lookup('vars', networks_lower[network] ~ '_host_routes') }}
              {% endif %}
              {%- endfor %}
              - type: ovs_bridge
                name: br-provider
                use_dhcp: false
              - type: ovs_bridge
                name: {{ neutron_physical_bridge_name }}
                mtu: {{ min_viable_mtu }}
                use_dhcp: false
                addresses:
                - ip_netmask: {{ lookup('vars', 'bgp_net1_ip') }}/30
                members:
                - type: interface
                  name: nic2
                  mtu: {{ min_viable_mtu }}
                  # force the MAC address of the bridge to this interface
                  primary: true
              - type: ovs_bridge
                name: {{ neutron_physical_bridge_name }}-2
                mtu: {{ min_viable_mtu }}
                use_dhcp: false
                addresses:
                - ip_netmask: {{ lookup('vars', 'bgp_net2_ip') }}/30
                members:
                - type: interface
                  name: nic3
                  mtu: {{ min_viable_mtu }}
                  # force the MAC address of the bridge to this interface
                  primary: true
              - type: interface
                name: lo
                addresses:
                - ip_netmask: {{ lookup('vars', 'bgp_main_net_ip') }}/32
                - ip_netmask: {{ lookup('vars', 'bgp_main_net6_ip') }}/128

         # These vars are for the network config templates themselves and are
         # considered EDPM network defaults.
         neutron_physical_bridge_name: br-ex
         neutron_public_interface_name: eth0
         # edpm_nodes_validation
         edpm_nodes_validation_validate_controllers_icmp: false
         edpm_nodes_validation_validate_gateway_icmp: false
         ctlplane_dns_nameservers:
         - 192.168.122.1
         # edpm firewall, change the allowed CIDR if needed
         edpm_sshd_allowed_ranges: ['192.168.122.0/24']
         edpm_frr_bgp_uplinks: ['nic2', 'nic3']
         edpm_frr_bgp_neighbor_password: f00barZ
         edpm_frr_bgp_ipv4_src_network: bgp_main_net
         edpm_frr_bgp_ipv6_src_network: bgp_main_net6
         edpm_frr_bgp_peers: ['100.64.1.5', '100.65.1.5']
         edpm_ovn_bgp_agent_expose_tenant_networks: true
         edpm_ovn_bgp_agent_local_ovn_routing: true
         edpm_ovn_bridge_mappings: ['bgp:br-provider']
         edpm_ovn_bgp_agent_local_ovn_external_nics: ['eth1', 'eth2']
         edpm_ovn_bgp_agent_local_ovn_peer_ips: ['100.64.1.5', '100.65.1.5']
         edpm_ovn_bgp_agent_exposing_method: ovn
         edpm_ovn_bgp_agent_provider_networks_pool_prefixes: '172.16.0.0/16'
